POST https://localhost:8443/jwt/tokens
Authorization: Basic ai5qYW1lc29uOnBhc3N3b3Jk

###
GET https://localhost:8443/manager.html
Authorization: Bearer eyJraWQiOiI2YWEyYjYwMS1mOTc5LTQ4NDAtYmI0NS0xNjRhZGU3Yzk5MzkiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqLmphbWVzb24iLCJleHAiOjE2ODg5OTAwMDAsImlhdCI6MTY4ODk4OTcwMCwianRpIjoiNmFhMmI2MDEtZjk3OS00ODQwLWJiNDUtMTY0YWRlN2M5OTM5IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9NQU5BR0VSIl19.szxgg-yu1f0-lF4xQRzT0oOiat_P6S9ZiYEaFXtfopM

###
POST https://localhost:8443/jwt/refresh
Authorization: Bearer eyJraWQiOiI2YWEyYjYwMS1mOTc5LTQ4NDAtYmI0NS0xNjRhZGU3Yzk5MzkiLCJlbmMiOiJBMTI4R0NNIiwiYWxnIjoiZGlyIn0..odHd3GRvcLyM2LY9.9U20mNe0w0pTA_MMhScApdG63372s-sXw6jd2t6RTSwazylUN6Hu7lgw22nMyUp18My-4sXWu5p_HZi9CAfvgB_nluO5n6tOX12oEyvHgX8bmQ33Qsu_9sGrr7uxCp6bT-2kkbGiVNObWtAIfUaalXK3Qlqv9K0ZLLuWp4CPFN8Jj5OjLzJ3IPCP0WS1sERXoo_Bw3nKRua0uARzO9YHzpXr.dYjmfWZ5fdd7XdhMbINd6g

###
POST https://localhost:8443/jwt/logout
Authorization: Bearer eyJraWQiOiI2YWEyYjYwMS1mOTc5LTQ4NDAtYmI0NS0xNjRhZGU3Yzk5MzkiLCJlbmMiOiJBMTI4R0NNIiwiYWxnIjoiZGlyIn0..odHd3GRvcLyM2LY9.9U20mNe0w0pTA_MMhScApdG63372s-sXw6jd2t6RTSwazylUN6Hu7lgw22nMyUp18My-4sXWu5p_HZi9CAfvgB_nluO5n6tOX12oEyvHgX8bmQ33Qsu_9sGrr7uxCp6bT-2kkbGiVNObWtAIfUaalXK3Qlqv9K0ZLLuWp4CPFN8Jj5OjLzJ3IPCP0WS1sERXoo_Bw3nKRua0uARzO9YHzpXr.dYjmfWZ5fdd7XdhMbINd6g
